### ISSUE TITLE
UI inconsistencies

### ISSUE THREAD

**Issue by the-Bruce** [dixonary/amphi-frontend#2]
Assuming the interface is supposed to be comparable with the rendering on chrome.
On the iPad, version fails to display the global playlist at any point. The Personal Queue and Add Song button render as usual, although stuck to the top.

On desktop Firefox, above ~980px wide everything normal, but below that only the global playlist renders

Devices tested:
iPad Air (3rd generation), iOS 13.3.1
iPad Mini (4th generation), iOS 13.3.1
Debian (Bullseye), Firefox 68.6.1esr
Debian (Bullseye), Chrome 80.0.3987.163

**Comment by the-Bruce** [comment]
Narrow Firefox
![image](https://user-images.githubusercontent.com/44057980/78561229-44a92600-780f-11ea-9462-6b5cc7f8dc31.png)

iPad
![Amphi](https://user-images.githubusercontent.com/44057980/78561615-f6485700-780f-11ea-90b1-f191747b7c0e.png)

**Comment by dixonary** [comment]
Thanks for the report. I'll take a look in due course.

**Comment by dixonary** [comment]
I am able to replicate in Firefox (cannot test on iPad).

**Comment by dixonary** [comment]
I suspect that this is a continuation of a known problem where Firefox does not correctly apply styles to a `<body>` tag which is specified as `display:flex`. Will work around.

**Comment by dixonary** [comment]
Firefox problem fixed by 5617147558b8389dcf737189fcf7a8d7a8791a99.

**Comment by dixonary** [comment]
I was able to replicate the ios issue on desktop Safari. This should be fixed by f20c18b38547e287dfd2af8565bbb922063c2b32. Please confirm?

**Comment by the-Bruce** [comment]
Ok, so it's fixed on Firefox and landscape view on the iPad, but portrait on the iPad is still missing the playlist while there is no video being played.

**Comment by dixonary** [comment]
Hopefully the latest commit (a5f1f7aec671129db90a200dd19fe44db95358d3) fixes this one, a couple of different sidebar things were changed. Stumbling around in the dark a little!

**Comment by dixonary** [comment]
I think these are fixed now? The now-playing move from fd6ffeb588e58fbc542aa7bd1e341039bc782aca may have introduced new inconsistencies.

**Comment by the-Bruce** [comment]
Looks good
